### ISSUE TITLE
Description in security definition doesn't support markdown

### ISSUE THREAD

**Issue by aberman** [bootprint/bootprint-openapi#65]
If you put Markdown in the description field for a security definition it is not rendered to HTML.  Instead, bootprint simply outputs the Markdown.

**Comment by nknapp** [comment]
It would be great if you could create a pull-request for a test-case (similar to the one for [tags](https://github.com/bootprint/bootprint-openapi/tree/master/test/tags) that also checks for the [conversion of markdown](https://github.com/bootprint/bootprint-openapi/blob/master/test/tags/tags-spec.js#L33). 

The fix is probably very similar to [this commit](https://github.com/bootprint/bootprint-openapi/commit/8d9abe18e147606228a1c3962eeffa8c198debfd), you just have to find the right [partial](https://github.com/bootprint/bootprint-openapi/blob/master/handlebars-partials.md) to put the `md`-helper in.

If all this is done and the tests are green, I will merge (or add you to the team so you can squash-merge it yourself). I'd then publish the to npm

**Comment by aberman** [comment]
Sorry for all the commits.  The last and most recent one is the correct one.

**Comment by nknapp** [comment]
Can you create a Pull-Request?

**Comment by aberman** [comment]
Did it, but there looks like some other test is failing unrelated to this.
