### ISSUE TITLE
Summary descriptions are empty

### ISSUE THREAD

**Issue by kristijan-ujevic** [bootprint/bootprint-openapi#78]
Is it possible to unify the description and summary in the swagger.json?

Because if i leave out summary and just add the description to an endpoint i'm left with an empty description in summary section, and vice-versa.

Can i set the tool to just use the "description" as "summary" if there is no "summary" defined in swagger.json?

**Comment by nknapp** [comment]
In my project, I am using the first line of description as summary. It's done while generating the swagger.json from other sources. 

You could create a [bootprint-module](https://github.com/bootprint/bootprint/blob/master/doc/modules.md) that inherits `bootprint-openapi` and adds [a custom preprocessor](https://github.com/bootprint/bootprint/blob/master/doc/config.md#preprocessor) to modify the input JSON.
If you want, you can publish this module on npm and use it instead of bootprint-openapi. 

It's currently not a thing that I would like to include into bootprint-openapi.
